trigger:
  branches:
    include:
      - main
      - feature/*

pr:
  branches:
    include:
      - main
      - feature/*

jobs:
  - job: Build
    steps:
      # Your build steps go here
      - task: UseNode@2
        inputs:
          versionSpec: '16.x'
        displayName: 'Set up Node.js'

      - script: |
          npm install
          npm run build
        displayName: 'Install Dependencies and Build'

  - job: NotifyFailure
    dependsOn: Build
    condition: failed()  # This will run only if the Build job fails
    steps:
      - script: |
          echo "The pipeline failed. Creating Jira issue..."

          # Define variables
          JIRA_URL="https://gowsigowsalyait923.atlassian.net"
          JIRA_PROJECT="MKT"
          JIRA_ISSUE_TYPE="Bug"
          AUTH_TOKEN=$(JIRA_API_TOKEN)
          BUILD_LINK="$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)"
          FAILED_BRANCH="$(Build.SourceBranchName)"

          # Make a POST request to Jira API to create the issue
          curl -X POST \
          -u "your-email@example.com:$AUTH_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{
                "fields": {
                  "project": { "key": "'$JIRA_PROJECT'" },
                  "summary": "Pipeline Failed: '$FAILED_BRANCH'",
                  "description": "The Azure DevOps pipeline failed for branch '$FAILED_BRANCH'.\n\nBuild details: '$BUILD_LINK'",
                  "issuetype": { "name": "'$JIRA_ISSUE_TYPE'" }
                }
              }' "$JIRA_URL/rest/api/2/issue"

          echo "Jira issue creation request sent."
        displayName: 'Notify Jira on Failure'



