name: Branch Name Validation

on:
  create:
    branches:
      - 'feature/*'  # Trigger on new feature branches

jobs:
  validate-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check Branch Naming Convention
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          # Validate the branch name against the pattern 'feature/MKT-<number>'
          if [[ ! "$BRANCH_NAME" =~ ^feature/MKT-[0-9]+$ ]]; then
            echo "Branch name does not match the required pattern 'feature/MKT-<story_number>'"
            echo "Deleting branch $BRANCH_NAME"
            git push origin --delete $BRANCH_NAME
            exit 1
          else
            echo "Branch name is valid: $BRANCH_NAME"
          fi
